ALTER TABLE participant_stats
    ADD COLUMN IF NOT EXISTS item0 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS item1 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS item2 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS item3 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS item4 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS item5 INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS item6 INTEGER NOT NULL DEFAULT 0;
